fix: exclude etag from field_behavior lints
googleapis/api-linter pull request #1009
Opened 2022-09-06 21:46 UTC by noahdietz

Fixes #977.

In a separate PR perhaps we should add a rule to enforce that `etag` should not have any field_behavior annotations at all.

2022-09-06 22:05 UTC, alin04 approved these changes

2022-09-06 22:32 UTC, shwoodard requested changes
I think I would rather have a `const etagFieldName = "etag"` and have all of the `!excludeFields.Contains(f.GetName())` just be `f.GetName() != etagFieldName` rather than having a `stringset` with one value, imho.

2022-09-06 22:32 UTC, shwoodard commented on rules/aip0203/aip0203.go
> +
I think this can be just,

```go
var excludeFields = stringset.New("etag")
```

2022-09-06 22:35 UTC, noahdietz commented on rules/aip0203/aip0203.go
> +
Yep! Done.

2022-09-06 22:36 UTC, noahdietz commented
> I think I would rather have a `const etagFieldName = "etag"` and have all of the `!excludeFields.Contains(f.GetName())` just be `f.GetName() != etagFieldName` rather than having a `stringset` with one value, imho.

I don't have another example of another standard field, but I can imagine there might be others, which is why I started with `stringset`. For example, I could see `string name` on the Resource being excluded from all of these. Just easier to expand later. Still want it changed?

2022-09-06 22:43 UTC, shwoodard commented
> I don't have another example of another standard field, but I can imagine there might be others, which is why I started with stringset. For example, I could see string name on the Resource being excluded from all of these. Just easier to expand later. Still want it changed?

Ack. Agreed. Can we change the variable name to `standardFields`?

2022-09-06 22:46 UTC, noahdietz commented
> Ack. Agreed. Can we change the variable name to `standardFields`?

Done!

2022-09-06 22:48 UTC, shwoodard approved these changes

2022-09-06 22:55 UTC, GregFurmanek commented
I am not sold on the standardFields name. It doesn't seem to describe the intended usage.

2022-09-06 22:58 UTC, shwoodard commented
> I am not sold on the standardFields name. It doesn't seem to describe the intended usage.

The variable name for a thing should say what it is and the behavior or how it is used should be demonstrated by the code, in this case, `!....Contains(...)`

2022-09-07 00:04 UTC, noahdietz commented
I'm going to merge this. The variable name can be discussed here and updated in another PR if necessary.

2022-09-07 00:04 UTC, merged

2022-09-07 15:39 UTC, GregFurmanek commented
@shwoodard So we have named it standardFields? What are standard fields?
I think this use case is quite specific: Fields excluded from evaluation for specific rules.

"StandardFields" gives the reader no indication what this variable is going to be used for,
neither does `!...Contains(...)` for that matter.

I think making someone read the implementation to figure out what a variable is used for is
not vary kind way to write code.