Enforce OUTPUT_ONLY behavior for State enums.
googleapis/api-linter pull request #1127
Opened 2023-03-30 21:51 UTC by hoskeri

google.aip.dev/216 calls for `State` enums to be
OUTPUT_ONLY.

Add a rule that requires OUTPUT_ONLY for fields which have an enum type ending with `State`.

Note that the AIP does not mention rules for the *field name* for state fields, we ignore the field name in the linter.

2023-03-30 22:04 UTC, noahdietz commented
You will need to add a documentation page for this to ./docs/rules/aip0216. Take a look at some other examples, copy one and change it up to match this rule.

2023-04-03 23:39 UTC, hoskeri commented
> You will need to add a documentation page for this to ./docs/rules/aip0216. Take a look at some other examples, copy one and change it up to match this rule.

Added the documentation.

2023-04-04 15:12 UTC, noahdietz reviewed
Looks great, thanks @hoskeri . I think I want @shwoodard or @toumorokoshi to review as well though.

2023-04-04 15:36 UTC, shwoodard requested changes

2023-04-04 15:36 UTC, shwoodard commented on rules/aip0216/state_enum_output_only_test.go
All enum should have ENUM_NAME_UNSPECIFIED as the zero value. So, if the Enum is called FooState, the the first value should be FOO_STATE_UNSPECIFIED = 0;

2023-04-04 15:45 UTC, shwoodard commented
Yeah, changing the naming is all I'm advocating for since it's the field and that is OUTPUT_ONLY and not the enum. Thanks @noahdietz!

2023-04-04 19:19 UTC, hoskeri commented on rules/aip0216/state_enum_output_only.go
> +		}
> I think this is too restrictive. There are state enums that don't end in "State".

quoting https://google.aip.dev/216:

> Resources needing to communicate their state should use an enum, which should be called State (or, if more  specificity is required, end in the word State).

If they are not named according to this, we would not recognize them as state fields, and not enforce this, and other rules. 

If there is a way to annotate an arbitrary field as being a 'state' field and/or enum, we could match that and enforce these conventions on them as well.

2023-04-05 15:04 UTC, shwoodard commented on rules/aip0216/state_enum_output_only.go
> +		}
Ack. Thanks.

2023-04-05 15:07 UTC, shwoodard approved these changes

2023-04-05 15:07 UTC, shwoodard commented on rules/aip0216/state_field_output_only_test.go
> +		Name          string
This can be package private as it is not exposed to template. IOW, downcase `Name`.

2023-04-05 15:08 UTC, shwoodard commented
I approved this but left one comment. Please update.

2023-04-05 15:09 UTC, shwoodard commented
> Member

![image](https://user-images.githubusercontent.com/34149/230123833-4b478b82-252f-4323-9ae1-d718e4f55cd6.png)

This image depicts a good reason why **not** to force push.

2023-04-05 15:51 UTC, noahdietz approved these changes

2023-04-05 18:42 UTC, noahdietz commented
I will set this for automerge since we got double approval.

2023-04-05 18:43 UTC, merged