feat(AIP-133): add request-id-field for non-df API
googleapis/api-linter pull request #1155
Opened 2023-05-19 05:09 UTC by toumorokoshi

Corresponds to the change to https://github.com/aip-dev/google.aip.dev/pull/1019.

resource_id is now required regardless of declarative_friendly.

2023-05-19 23:20 UTC, shwoodard requested changes

2023-05-19 23:20 UTC, shwoodard commented on rules/aip0133/request_id_field_test.go
> +		{"InvalidRepeated", "repeated string book_id = 2;", problems},
Do these two differ? Remove one?

2023-05-20 17:44 UTC, toumorokoshi commented on rules/aip0133/request_id_field_test.go
> +		{"InvalidRepeated", "repeated string book_id = 2;", problems},
weird, must have copy-pasted a line before I committed. fixed.

2023-05-22 15:44 UTC, merged

2024-06-27 06:50 UTC, SsomsakTH commented
> Corresponds to the change to https://github.com/aip-dev/google.aip.dev/pull/1019.
> 
> resource_id is now required regardless of declarative_friendly.
> 
> fixes #1107

2024-06-27 06:52 UTC, SsomsakTH commented
> Corresponds to the change to https://github.com/aip-dev/google.aip.dev/pull/1019.
> 
> resource_id is now required regardless of declarative_friendly.
> 
> fixes #1107