feat: validate list parent resource_reference
googleapis/api-linter pull request #754
Opened 2021-02-10 23:57 UTC by noahdietz

This lints List*Request parent resource_reference annotations to check it does not reference the resource being listed.

2021-02-11 17:18 UTC, lukesneeringer requested changes
I wonder if we should go stronger and say to always use `child_type` with the resource.

2021-02-11 18:21 UTC, noahdietz commented
> I wonder if we should go stronger and say to always use `child_type` with the resource.

I think that would be reasonable, but previous advice has been that we can do either. There would be many API's in "violation" of this rule today if we enforced only `child_type`. Not a reason we shouldn't do it if we think it's right, but there was some merit to our existing practice that we will have to go back on.

I'm happy to change it if you think that is better though. LMK one way or the other.

2021-02-12 19:15 UTC, lukesneeringer commented
That is a fair point. Okay.

2021-02-12 19:16 UTC, lukesneeringer approved these changes

2021-02-12 19:16 UTC, lukesneeringer approved these changes

2021-02-12 19:16 UTC, merged